# Generated by Django 5.0.14 on 2025-09-18 13:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('icone', models.CharField(default='bi-utensils', max_length=50)),
                ('cor', models.CharField(default='#667eea', help_text='Cor em hexadecimal (ex: #667eea)', max_length=7)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('ingredientes', models.TextField(help_text='Lista de ingredientes separados por vírgula')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tamanho', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('U', 'Único')], default='U', max_length=1)),
                ('calorias', models.PositiveIntegerField(blank=True, help_text='Calorias aproximadas', null=True)),
                ('tempo_preparo', models.PositiveIntegerField(blank=True, help_text='Tempo de preparo em minutos', null=True)),
                ('nivel_picante', models.PositiveIntegerField(default=0, help_text='Nível de picante de 0 a 5', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('vegetariano', models.BooleanField(default=False)),
                ('vegano', models.BooleanField(default=False)),
                ('sem_gluten', models.BooleanField(default=False)),
                ('sem_lactose', models.BooleanField(default=False)),
                ('imagem', models.CharField(blank=True, help_text='URL da imagem do prato', max_length=500, null=True)),
                ('destaque', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pratos', to='cardapio.categoria')),
            ],
            options={
                'verbose_name': 'Prato',
                'verbose_name_plural': 'Pratos',
                'ordering': ['categoria__ordem', 'categoria__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nota', models.PositiveIntegerField(help_text='Nota de 1 a 5 estrelas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='cardapio.prato')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-created_at'],
            },
        ),
    ]
