# Generated by Django 5.0.14 on 2025-09-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='conservacao',
            field=models.TextField(blank=True, help_text='Instruções de conservação', null=True),
        ),
        migrations.AddField(
            model_name='prato',
            name='dicas_chef',
            field=models.TextField(blank=True, help_text='Dicas especiais do chef', null=True),
        ),
        migrations.AddField(
            model_name='prato',
            name='dificuldade',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], default='facil', max_length=20),
        ),
        migrations.AddField(
            model_name='prato',
            name='modo_preparo',
            field=models.TextField(blank=True, help_text='Instruções detalhadas de preparo', null=True),
        ),
        migrations.AddField(
            model_name='prato',
            name='rendimento',
            field=models.CharField(blank=True, help_text='Ex: 4 porções, 1 unidade', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prato',
            name='temperatura_servico',
            field=models.CharField(blank=True, help_text='Ex: Quente, Frio, Morno', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prato',
            name='tempo_preparo_total',
            field=models.PositiveIntegerField(blank=True, help_text='Tempo total de preparo em minutos', null=True),
        ),
        migrations.AddField(
            model_name='prato',
            name='utensilios_necessarios',
            field=models.TextField(blank=True, help_text='Lista de utensílios necessários', null=True),
        ),
        migrations.AddField(
            model_name='prato',
            name='valor_nutricional',
            field=models.TextField(blank=True, help_text='Informações nutricionais detalhadas', null=True),
        ),
    ]
