# Generated by Django 5.0.14 on 2025-09-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_prato_conservacao_prato_dicas_chef_prato_dificuldade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='montagem_prato',
            field=models.TextField(blank=True, help_text='Instruções de montagem e apresentação do prato', null=True),
        ),
        migrations.AddField(
            model_name='prato',
            name='quantitativo_ingredientes',
            field=models.TextField(blank=True, help_text='Quantidades específicas dos ingredientes', null=True),
        ),
    ]
