# Generated by Django 5.0.14 on 2025-09-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_prato_montagem_prato_prato_quantitativo_ingredientes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
