# Generated by Django 5.0.14 on 2025-09-25 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0004_delete_avaliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'cardapio_produto',
            },
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prato', models.CharField(max_length=200, unique=True)),
                ('descricao', models.TextField()),
                ('ingredientes', models.TextField()),
                ('modo_preparo', models.TextField()),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica', to='cardapio.categoria')),
            ],
            options={
                'verbose_name': 'Ficha Técnica',
                'verbose_name_plural': 'Fichas Técnicas',
                'db_table': 'cardapio_ficha_tecnica',
            },
        ),
        migrations.CreateModel(
            name='FichaTecnicaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_caseira', models.CharField(max_length=200)),
                ('quantidade', models.FloatField()),
                ('unidade', models.CharField(max_length=20)),
                ('ficha_tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica_produto', to='cardapio.fichatecnica')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica_produto', to='cardapio.produto')),
            ],
            options={
                'verbose_name': 'Ficha Técnica Produto',
                'verbose_name_plural': 'Fichas Técnicas Produtos',
                'db_table': 'cardapio_ficha_produto',
            },
        ),
    ]
