# Generated by Django 5.0.14 on 2025-09-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0005_produto_fichatecnica_fichatecnicaproduto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichatecnica',
            name='ingredientes',
        ),
    ]
