# Generated by Django 5.0.14 on 2025-09-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0006_remove_fichatecnica_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnica',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='modo_preparo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichatecnicaproduto',
            name='med_caseira',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fichatecnicaproduto',
            name='unidade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
