# Generated by Django 5.0.14 on 2025-09-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0007_alter_fichatecnica_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnicaproduto',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
