# Generated by Django 5.0.14 on 2025-09-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0008_alter_fichatecnicaproduto_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnicaproduto',
            name='quantidade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
