# Generated by Django 5.0.14 on 2025-10-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0009_alter_fichatecnicaproduto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnica',
            name='imagem',
            field=models.CharField(blank=True, help_text='URL da imagem da ficha técnica', max_length=500, null=True),
        ),
    ]
