# Generated by Django 5.0.14 on 2025-10-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0010_fichatecnica_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnica',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem da ficha técnica', null=True, upload_to='fichas_tecnicas/'),
        ),
    ]
