# Generated by Django 5.0.14 on 2025-10-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0011_alter_fichatecnica_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem do prato', null=True, upload_to='pratos/'),
        ),
    ]
