# Generated by Django 5.0.14 on 2025-10-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0012_alter_prato_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tempo_preparo',
            field=models.PositiveIntegerField(default=0, help_text='Tempo de preparo em minutos'),
        ),
        migrations.DeleteModel(
            name='Prato',
        ),
    ]
