# Generated by Django 5.0.9 on 2024-11-06 02:27

import RH.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.TextField(choices=[('BANCO DO BRASIL', 'BANCO DO BRASIL'), ('CAIXA ECONOMICA', 'CAIXA ECONOMICA'), ('ITAU', 'ITAU'), ('BRADESCO', 'BRADESCO'), ('SANTANDER', 'SANTANDER'), ('NUBANK', 'NUBANK'), ('INTER', 'INTER')])),
                ('agencia', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_BI', models.IntegerField()),
                ('empresa', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotacao', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.TextField(max_length=20)),
                ('intervalo', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.TextField(max_length=6, verbose_name='Matrícula')),
                ('dt_admissao', models.DateField(verbose_name='Data Admissão')),
                ('dt_demissao', models.DateField(verbose_name='Data Demissão')),
                ('nome', models.TextField(max_length=100, verbose_name='Nome')),
                ('dt_nascimento', models.DateField(verbose_name='Data Nascimento')),
                ('sexo', models.TextField(choices=[('F', 'Masculino'), ('M', 'Feminino'), ('T', 'Todes')], verbose_name='Sexo')),
                ('naturalidade', models.TextField(max_length=6, verbose_name='Naturalidade')),
                ('rg', models.TextField(max_length=20, verbose_name='RG')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('conta_bancaria', models.TextField(max_length=20, verbose_name='Conta Bancária')),
                ('motivo_contratacao', models.TextField(max_length=20, verbose_name='Motivo da Contração')),
                ('dt_primeiro_termino', models.DateField(verbose_name='Data 1º Termino')),
                ('dt_segundo_termino', models.DateField(verbose_name='Data 2º Termino')),
                ('dt_contrato_experiencia', models.DateField(verbose_name='Data Contrato Experiência')),
                ('dt_ultimo_aso', models.DateField(verbose_name='Data Último ASO')),
                ('dt_aso_periodico', models.DateField(verbose_name='Data ASO Periódico')),
                ('fone_fixo', models.TextField(max_length=20, verbose_name='Fone Fixo')),
                ('fone_celular', models.TextField(max_length=20, verbose_name='Fone Celular')),
                ('folga', models.TextField(choices=[('SEGUNDA-FEIRA', 'SEGUNDA-FEIRA'), ('TERÇA-FEIRA', 'TERÇA-FEIRA'), ('QUARTA-FEIRA', 'QUARTA-FEIRA'), ('QUINTA-FEIRA', 'QUINTA-FEIRA'), ('SEXTA-FEIRA', 'SEXTA-FEIRA'), ('SABADO', 'SABADO'), ('DOMINGO', 'DOMINGO')], verbose_name='Folga')),
                ('plano_saude_titular', models.TextField(choices=[('S', 'SIM'), ('N', 'NÃO')], verbose_name='Plano de Saúde Titular')),
                ('plano_saude_dependente', models.TextField(choices=[('S', 'SIM'), ('N', 'NÃO')], verbose_name='Plano de Saúde Dependente')),
                ('plano_odonto_titular', models.TextField(choices=[('S', 'SIM'), ('N', 'NÃO')], verbose_name='Plano Odonto Titular')),
                ('plano_odonto_dependente', models.TextField(choices=[('S', 'SIM'), ('N', 'NÃO')], verbose_name='Plano Odonto Dependente')),
                ('vale_transporte', models.TextField(choices=[('S', 'SIM'), ('N', 'NÃO')], verbose_name='Vale Transporte')),
                ('salario_familia', models.TextField(choices=[('S', 'SIM'), ('N', 'NÃO')], verbose_name='Salário Família')),
                ('dependentes', models.TextField(choices=[('S', 'SIM'), ('N', 'NÃO')], verbose_name='Dependente')),
                ('salario_fixo', models.FloatField(default=0, verbose_name='Salário Fixo')),
                ('salario_compl', models.FloatField(default=0, verbose_name='Salário Complementar')),
                ('cargo', models.ForeignKey(on_delete=RH.models.Cargo, to='RH.cargo')),
                ('lotacao', models.ForeignKey(on_delete=RH.models.Lotacao, to='RH.lotacao')),
                ('tipo_contrato', models.ForeignKey(on_delete=RH.models.TipoContrato, to='RH.tipocontrato')),
                ('turno', models.ForeignKey(on_delete=RH.models.Turno, to='RH.turno')),
            ],
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.cargo')),
                ('funcionario', models.ForeignKey(on_delete=RH.models.Funcionario, to='RH.funcionario')),
            ],
        ),
    ]
