# Generated by Django 5.0.9 on 2024-11-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='agencia',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='banco',
            name='banco',
            field=models.CharField(choices=[('BANCO DO BRASIL', 'BANCO DO BRASIL'), ('CAIXA ECONOMICA', 'CAIXA ECONOMICA'), ('ITAU', 'ITAU'), ('BRADESCO', 'BRADESCO'), ('SANTANDER', 'SANTANDER'), ('NUBANK', 'NUBANK'), ('INTER', 'INTER')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='empresa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='conta_bancaria',
            field=models.CharField(max_length=20, verbose_name='Conta Bancária'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='dependentes',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=10, verbose_name='Dependente'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='folga',
            field=models.CharField(choices=[('SEGUNDA-FEIRA', 'SEGUNDA-FEIRA'), ('TERÇA-FEIRA', 'TERÇA-FEIRA'), ('QUARTA-FEIRA', 'QUARTA-FEIRA'), ('QUINTA-FEIRA', 'QUINTA-FEIRA'), ('SEXTA-FEIRA', 'SEXTA-FEIRA'), ('SABADO', 'SABADO'), ('DOMINGO', 'DOMINGO')], max_length=30, verbose_name='Folga'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='fone_celular',
            field=models.CharField(max_length=20, verbose_name='Fone Celular'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='fone_fixo',
            field=models.CharField(max_length=20, verbose_name='Fone Fixo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(max_length=6, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='motivo_contratacao',
            field=models.CharField(max_length=20, verbose_name='Motivo da Contração'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='naturalidade',
            field=models.CharField(max_length=6, verbose_name='Naturalidade'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='plano_odonto_dependente',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=10, verbose_name='Plano Odonto Dependente'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='plano_odonto_titular',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=10, verbose_name='Plano Odonto Titular'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='plano_saude_dependente',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=10, verbose_name='Plano de Saúde Dependente'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='plano_saude_titular',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=10, verbose_name='Plano de Saúde Titular'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(max_length=20, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario_familia',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=10, verbose_name='Salário Família'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(choices=[('F', 'Masculino'), ('M', 'Feminino'), ('T', 'Todes')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='vale_transporte',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=10, verbose_name='Vale Transporte'),
        ),
        migrations.AlterField(
            model_name='lotacao',
            name='lotacao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipocontrato',
            name='tipo_contrato',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='turno',
            name='intervalo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='turno',
            name='turno',
            field=models.CharField(max_length=20),
        ),
    ]
