# Generated by Django 5.0.9 on 2024-11-06 02:55

import RH.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0002_alter_banco_agencia_alter_banco_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='empresa',
            field=models.ForeignKey(default=8, on_delete=RH.models.Empresa, to='RH.empresa'),
            preserve_default=False,
        ),
    ]
