# Generated by Django 5.0.9 on 2024-11-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0003_funcionario_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Funcionario',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
    ]
