# Generated by Django 5.0.9 on 2024-11-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0004_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Funcionario',
            name='naturalidade',
            field=models.CharField(max_length=40, verbose_name='Naturalidade'),
        ),
    ]
