# Generated by Django 5.0.9 on 2024-11-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0005_alter_funcionario_naturalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Funcionario',
            name='conta_bancaria',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta Bancária'),
        ),
        migrations.AlterField(
            model_name='Funcionario',
            name='dependentes',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=10, null=True, verbose_name='Dependente'),
        ),
        migrations.AlterField(
            model_name='Funcionario',
            name='dt_aso_periodico',
            field=models.DateField(blank=True, null=True, verbose_name='Data ASO Periódico'),
        ),
        migrations.AlterField(
            model_name='Funcionario',
            name='dt_contrato_experiencia',
            field=models.DateField(blank=True, null=True, verbose_name='Data Contrato Experiência'),
        ),
        migrations.AlterField(
            model_name='Funcionario',
            name='dt_demissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Demissão'),
        ),
        migrations.AlterField(
            model_name='Funcionario',
            name='dt_primeiro_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Data 1º Termino'),
        ),
        migrations.AlterField(
            model_name='Funcionario',
            name='dt_segundo_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Data 2º Termino'),
        ),
        migrations.AlterField(
            model_name='Funcionario',
            name='dt_ultimo_aso',
            field=models.DateField(blank=True, null=True, verbose_name='Data Último ASO'),
        ),
        migrations.AlterField(
            model_name='Funcionario',
            name='folga',
            field=models.CharField(blank=True, choices=[('SEGUNDA-FEIRA', 'SEGUNDA-FEIRA'), ('TERÇA-FEIRA', 'TERÇA-FEIRA'), ('QUARTA-FEIRA', 'QUARTA-FEIRA'), ('QUINTA-FEIRA', 'QUINTA-FEIRA'), ('SEXTA-FEIRA', 'SEXTA-FEIRA'), ('SABADO', 'SABADO'), ('DOMINGO', 'DOMINGO')], max_length=30, null=True, verbose_name='Folga'),
        ),
        migrations.AlterField(
            model_name='Funcionario',
            name='fone_celular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fone Celular'),
        ),
        migrations.AlterField(
            model_name='Funcionario',
            name='fone_fixo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fone Fixo'),
        ),
        migrations.AlterField(
            model_name='Funcionario',
            name='motivo_contratacao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Motivo da Contração'),
        ),
        migrations.AlterField(
            model_name='Funcionario',
            name='plano_odonto_dependente',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=10, null=True, verbose_name='Plano Odonto Dependente'),
        ),
        migrations.AlterField(
            model_name='Funcionario',
            name='plano_odonto_titular',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=10, null=True, verbose_name='Plano Odonto Titular'),
        ),
        migrations.AlterField(
            model_name='Funcionario',
            name='plano_saude_dependente',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=10, null=True, verbose_name='Plano de Saúde Dependente'),
        ),
        migrations.AlterField(
            model_name='Funcionario',
            name='plano_saude_titular',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=10, null=True, verbose_name='Plano de Saúde Titular'),
        ),
        migrations.AlterField(
            model_name='Funcionario',
            name='salario_familia',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=10, null=True, verbose_name='Salário Família'),
        ),
        migrations.AlterField(
            model_name='Funcionario',
            name='vale_transporte',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=10, null=True, verbose_name='Vale Transporte'),
        ),
    ]
