# Generated by Django 5.0.9 on 2024-12-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0006_alter_funcionario_conta_bancaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='deleted',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='dependentes',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1, null=True, verbose_name='Dependente'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='plano_odonto_dependente',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1, null=True, verbose_name='Plano Odonto Dependente'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='plano_odonto_titular',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1, null=True, verbose_name='Plano Odonto Titular'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='plano_saude_dependente',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1, null=True, verbose_name='Plano de Saúde Dependente'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='plano_saude_titular',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1, null=True, verbose_name='Plano de Saúde Titular'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario_familia',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1, null=True, verbose_name='Salário Família'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='vale_transporte',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1, null=True, verbose_name='Vale Transporte'),
        ),
    ]
