# Generated by Django 5.0.9 on 2024-12-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0007_funcionario_deleted_alter_funcionario_dependentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='deleted',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
