# Generated by Django 5.0.9 on 2024-12-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0008_alter_funcionario_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='deleted',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
    ]
