# Generated by Django 5.0.9 on 2024-12-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0009_alter_funcionario_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='intervalo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='turno',
            field=models.CharField(max_length=40),
        ),
    ]
