# Generated by Django 5.0.9 on 2024-12-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0010_alter_turno_intervalo_alter_turno_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='turno',
            field=models.CharField(max_length=100),
        ),
    ]
