# Generated by Django 5.0.9 on 2024-12-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0011_alter_turno_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folga', models.CharField(max_length=100)),
            ],
        ),
    ]
