# Generated by Django 5.0.9 on 2024-12-03 17:31

import RH.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0012_folga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='folga',
            field=models.ForeignKey(blank=True, null=True, on_delete=RH.models.Folga, to='RH.folga'),
        ),
    ]
