# Generated by Django 5.0.9 on 2024-12-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0013_alter_funcionario_folga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Naturalidade'),
        ),
    ]
