# Generated by Django 5.0.9 on 2024-12-03 17:48

import RH.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0014_alter_funcionario_naturalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=RH.models.Cargo, to='RH.cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='lotacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=RH.models.Lotacao, to='RH.lotacao'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=RH.models.TipoContrato, to='RH.tipocontrato'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=RH.models.Turno, to='RH.turno'),
        ),
    ]
