# Generated by Django 5.0.9 on 2024-12-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0015_alter_funcionario_cargo_alter_funcionario_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Matrícula'),
        ),
    ]
