# Generated by Django 5.0.9 on 2024-12-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0016_alter_funcionario_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='motivo_contratacao',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Motivo da Contração'),
        ),
    ]
