# Generated by Django 5.0.9 on 2024-12-03 18:26

import RH.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0017_alter_funcionario_motivo_contratacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=RH.models.Empresa, to='RH.empresa'),
        ),
    ]
