# Generated by Django 5.0.9 on 2024-12-03 18:50

import RH.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0018_alter_funcionario_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='dt_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Admissão'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=RH.models.Empresa, to='RH.empresa'),
            preserve_default=False,
        ),
    ]
