# Generated by Django 5.0.9 on 2024-12-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0019_alter_funcionario_dt_admissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='dt_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Nascimento'),
        ),
    ]
