# Generated by Django 5.0.9 on 2024-12-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0020_alter_funcionario_dt_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='status',
            field=models.CharField(choices=[('A', 'ATIVO'), ('F', 'AFASTADO'), ('D', 'DEMITIDO')], default='A', max_length=1),
        ),
    ]
