# Generated by Django 5.0.9 on 2025-01-05 18:27

import RH.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0021_funcionario_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='configGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_primeiro_termino_exp', models.IntegerField()),
                ('dias_segundo_termino_exp', models.IntegerField()),
                ('empresa', models.ForeignKey(on_delete=RH.models.Empresa, to='RH.empresa')),
            ],
        ),
    ]
