# Generated by Django 5.0.9 on 2025-02-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0023_banco_created_banco_updated_banco_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banco',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='configgeral',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='folga',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='lotacao',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='tipocontrato',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='tipoevento',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='usuario',
        ),
    ]
