# Generated by Django 5.0.9 on 2025-02-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0024_remove_banco_usuario_remove_cargo_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='Obs',
            field=models.TextField(max_length=250, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
