# Generated by Django 5.0.9 on 2025-03-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0025_alter_evento_obs_alter_evento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('T', 'Todes')], max_length=1, verbose_name='Sexo'),
        ),
    ]
