# Generated by Django 5.0.9 on 2025-06-25 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0026_alter_funcionario_sexo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='data',
        ),
        migrations.AddField(
            model_name='evento',
            name='vagas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vagas'),
        ),
        migrations.CreateModel(
            name='DiaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Dia')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Hora de Fim')),
                ('observacoes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observações')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_evento', to='RH.evento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data', 'hora_inicio'],
                'unique_together': {('evento', 'data')},
            },
        ),
        migrations.CreateModel(
            name='FrequenciaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'PRESENTE'), ('F', 'FALTA'), ('J', 'JUSTIFICADA'), ('A', 'ATRASO'), ('S', 'SAÍDA_ANTECIPADA')], default='P', max_length=1, verbose_name='Status')),
                ('hora_entrada', models.TimeField(blank=True, null=True, verbose_name='Hora de Entrada')),
                ('hora_saida', models.TimeField(blank=True, null=True, verbose_name='Hora de Saída')),
                ('observacoes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observações')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('controle_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='RH.controleevento')),
                ('dia_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='RH.diaevento')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='frequencias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dia_evento__data', 'controle_evento__funcionario__nome'],
                'unique_together': {('controle_evento', 'dia_evento')},
            },
        ),
    ]
