# Generated by Django 5.0.9 on 2025-07-03 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0027_remove_evento_data_evento_vagas_diaevento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absenteismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('dias_trabalho', models.IntegerField(verbose_name='Dias Trabalho')),
                ('dias_falta', models.IntegerField(verbose_name='Dias Falta')),
                ('dias_justificados', models.IntegerField(verbose_name='Dias Justificados')),
                ('dias_atraso', models.IntegerField(verbose_name='Dias Atraso')),
                ('dias_saida_antecipada', models.IntegerField(verbose_name='Dias Saída Antecipada')),
                ('dias_extras', models.IntegerField(verbose_name='Dias Extras')),
                ('dias_ferias', models.IntegerField(verbose_name='Dias Férias')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.funcionario')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'absenteismo',
                'ordering': ['data', 'funcionario'],
                'unique_together': {('funcionario', 'data')},
            },
        ),
    ]
