# Generated by Django 5.0.14 on 2025-08-18 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0028_absenteismo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RH.empresa'),
            preserve_default=False,
        ),
    ]
