# Generated by Django 5.0.14 on 2026-02-13 09:11

import RH.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0029_evento_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='operacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=RH.models.Operacao, to='RH.operacao'),
        ),
    ]
