# Generated by Django 5.0.9 on 2025-02-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_tarefa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='paramentros',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='status',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='status_processo',
            field=models.CharField(blank=True, choices=[('E', 'Executando'), ('P', 'Parado'), ('S', 'Finalizado'), ('F', 'Falhou')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='status_tarefa',
            field=models.CharField(blank=True, choices=[('E', 'Habilitado'), ('D', 'Desabilitado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='path',
            field=models.CharField(max_length=255),
        ),
    ]
