# Generated by Django 5.0.9 on 2025-02-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_remove_tarefa_paramentros_remove_tarefa_resultado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='tipo',
            field=models.CharField(blank=True, choices=[('GERAL', 'GERAL'), ('INDIVIDUAL', 'INDIVIDUAL')], max_length=30, null=True),
        ),
    ]
