# Generated by Django 5.0.9 on 2025-04-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_tarefa_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='grupo',
            field=models.CharField(blank=True, choices=[('FINANCEIRO', 'FINANCEIRO'), ('VENDAS', 'VENDAS'), ('DIMENSOES', 'DIMENSOES'), ('COMPRAS', 'COMPRAS')], max_length=50, null=True),
        ),
    ]
