# Generated by Django 5.0.9 on 2025-02-19 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(default=0)),
                ('solucao', models.CharField(max_length=10)),
                ('mae', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos', to='Gestao.conta')),
                ('dre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestao.dre')),
            ],
        ),
    ]
