# Generated by Django 5.0.9 on 2025-02-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dre',
            name='nivel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
