# Generated by Django 5.0.9 on 2025-02-19 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0002_alter_dre_nivel'),
        ('RH', '0025_alter_evento_obs_alter_evento_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.FloatField(default=0)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestao.conta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RH.empresa')),
            ],
        ),
    ]
