# Generated by Django 5.0.9 on 2025-02-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0003_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='analitica',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='conta',
            name='natureza',
            field=models.CharField(blank=True, choices=[('S', 'Saida'), ('E', 'Entrada')], max_length=30, null=True),
        ),
    ]
