# Generated by Django 5.0.9 on 2025-02-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0004_conta_analitica_conta_natureza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='nivel',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='solucao',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
