# Generated by Django 5.0.9 on 2025-02-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0005_alter_conta_nivel_alter_conta_solucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='natureza',
            field=models.CharField(blank=True, choices=[('Saida', 'Saida'), ('Entrada', 'Entrada')], max_length=30, null=True),
        ),
    ]
