# Generated by Django 5.0.9 on 2025-02-20 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0006_alter_conta_natureza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='dre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestao.dre'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='mae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos', to='Gestao.conta'),
        ),
    ]
