# Generated by Django 5.0.9 on 2025-02-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0007_alter_conta_dre_alter_conta_mae'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='ordem',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
