# Generated by Django 5.0.9 on 2025-02-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0008_conta_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='conta',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='dre',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dre',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
