# Generated by Django 5.0.9 on 2025-02-21 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0009_conta_created_conta_updated_dre_created_dre_updated_and_more'),
        ('RH', '0025_alter_evento_obs_alter_evento_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento_Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestao.conta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RH.empresa')),
            ],
        ),
    ]
