# Generated by Django 5.0.9 on 2025-02-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0010_lancamento_manual'),
        ('RH', '0025_alter_evento_obs_alter_evento_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lancamento_Manual',
            new_name='Lancamento',
        ),
    ]
