# Generated by Django 5.0.9 on 2025-03-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0011_rename_lancamento_manual_lancamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='nivel_dre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhosDre', to='Gestao.conta'),
        ),
    ]
