# Generated by Django 5.0.9 on 2025-04-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0012_conta_nivel_dre'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='operacao',
            field=models.CharField(choices=[('DRE', 'DRE'), ('DFC', 'DFC'), ('TODAS', 'TODAS')], default='Todas', max_length=30),
        ),
    ]
