# Generated by Django 5.0.9 on 2025-04-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0013_conta_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='operacao',
            field=models.CharField(choices=[('DRE', 'DRE'), ('DFC', 'DFC'), ('Todas', 'Todas')], default='Todas', max_length=30),
        ),
    ]
