# Generated by Django 5.0.9 on 2025-04-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0014_alter_conta_operacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dfc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('dfc', models.CharField(max_length=100)),
                ('nivel1', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel2', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
