# Generated by Django 5.0.9 on 2025-04-23 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0015_dfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='dfc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestao.dfc'),
        ),
    ]
