# Generated by Django 5.0.9 on 2025-04-30 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0016_conta_dfc'),
        ('RH', '0026_alter_funcionario_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Conta_Financeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('saldo_inicial', models.FloatField()),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestao.bancos')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RH.empresa')),
            ],
        ),
    ]
