# Generated by Django 5.0.9 on 2025-04-30 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0017_bancos_conta_financeira'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bancos',
            new_name='Banco',
        ),
    ]
