# Generated by Django 5.0.9 on 2025-06-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0019_centrocusto_lancamento_centro_custo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
