# Generated by Django 5.0.9 on 2025-07-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0021_orcamento_otimista_orcamento_pessimista_configgeral'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configgeral',
            options={'verbose_name': 'Configuração Geral', 'verbose_name_plural': 'Configurações Gerais'},
        ),
    ]
