# Generated by Django 5.0.9 on 2025-07-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0022_alter_configgeral_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='cenario',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
