# Generated by Django 5.0.14 on 2025-10-24 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0024_fornecedor'),
        ('RH', '0029_evento_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='reponsavel_conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestao.conta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RH.empresa')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
