# Generated by Django 5.0.14 on 2026-04-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0026_encerramentoorcamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'db_table': 'gestao_feriado',
                'ordering': ['data'],
            },
        ),
    ]
