# Generated by Django 5.0.9 on 2024-12-09 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=100)),
                ('sub_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='PerfilMenus.menus')),
            ],
            options={
                'db_table': 'Menus',
                'ordering': ['menu', 'sub_menu'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PerfilMenus.menus')),
            ],
            options={
                'db_table': 'Perfil',
                'ordering': ['group__name'],
            },
        ),
    ]
