# Generated by Django 5.0.9 on 2024-12-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PerfilMenus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menus',
            new_name='Menu',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='Menu',
        ),
    ]
