# Generated by Django 5.0.9 on 2024-12-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerfilMenus', '0002_rename_menus_menu_alter_menu_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['menu']},
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
