# Generated by Django 5.0.9 on 2024-12-09 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerfilMenus', '0003_alter_menu_options_alter_menu_url'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acoes_Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Perfil',
            new_name='PerfilMenu',
        ),
        migrations.CreateModel(
            name='Acoes_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PerfilMenus.menu')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PerfilMenus.acoes_tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Acoes_Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PerfilMenus.acoes_link')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
        ),
    ]
