# Generated by Django 5.0.9 on 2025-06-25 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerfilMenus', '0004_acoes_tipo_rename_perfil_perfilmenu_acoes_link_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'acao_tipo',
            },
        ),
        migrations.RemoveField(
            model_name='acoes_link',
            name='acao',
        ),
        migrations.RemoveField(
            model_name='acoes_link',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='acoes_perfil',
            name='acao',
        ),
        migrations.RemoveField(
            model_name='acoes_perfil',
            name='group',
        ),
        migrations.RemoveField(
            model_name='perfilmenu',
            name='group',
        ),
        migrations.RemoveField(
            model_name='perfilmenu',
            name='menu',
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='sub_menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='nome',
            field=models.CharField(default='teste', max_length=50),
        ),
        migrations.AddField(
            model_name='menu',
            name='pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='PerfilMenus.menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PerfilMenus.menu')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PerfilMenus.acaotipo')),
            ],
            options={
                'db_table': 'acao',
                'unique_together': {('menu', 'acao')},
            },
        ),
        migrations.CreateModel(
            name='PermissaoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PerfilMenus.acao')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'db_table': 'permissao_grupo',
                'unique_together': {('grupo', 'acao')},
            },
        ),
        migrations.DeleteModel(
            name='Acoes_Tipo',
        ),
        migrations.DeleteModel(
            name='Acoes_Link',
        ),
        migrations.DeleteModel(
            name='Acoes_Perfil',
        ),
        migrations.DeleteModel(
            name='PerfilMenu',
        ),
    ]
